#!/bin/bash

set -euo pipefail

PROJECT_DIR="${1:-/home/ubuntu/modarepo}"

if [ ! -d "$PROJECT_DIR" ]; then
    echo "ERROR: Project directory not found: $PROJECT_DIR"
    exit 1
fi

cd "$PROJECT_DIR"

required_vars=(
    PUBLIC_IP
    ORACLE_ACCESS_KEY_ID
    ORACLE_SECRET_ACCESS_KEY
    ORACLE_REGION
    ORACLE_BUCKET_NAME
    ORACLE_NAMESPACE
    ORACLE_ENDPOINT
)

for var_name in "${required_vars[@]}"; do
    if [ -z "${!var_name:-}" ]; then
        echo "ERROR: Required variable is missing: $var_name"
        exit 1
    fi
done

DB_HOST="${DB_HOST:-postgres}"
DB_PORT="${DB_PORT:-5432}"
DB_USER="${DB_USER:-moda_user}"
DB_PASSWORD="${DB_PASSWORD:-moda_pass}"
DB_NAME="${DB_NAME:-modadb}"
DATABASE_URL="${DATABASE_URL:-postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=public}"

REDIS_HOST="${REDIS_HOST:-redis}"
REDIS_PORT="${REDIS_PORT:-6379}"
API_URL="${API_URL:-http://backend:3001}"
NEXT_PUBLIC_API_URL="${NEXT_PUBLIC_API_URL:-https://${PUBLIC_IP}}"
STRIPE_SECRET_KEY="${STRIPE_SECRET_KEY:-}"
STRIPE_WEBHOOK_SECRET="${STRIPE_WEBHOOK_SECRET:-}"
JWT_SECRET="${JWT_SECRET:-}"
FRONTEND_URL="${FRONTEND_URL:-https://${PUBLIC_IP}}"

cat > .env.production <<EOF
# Generated by deploy/generate-env-production.sh
PUBLIC_IP=${PUBLIC_IP}

# Backend API
API_URL=${API_URL}
NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
FRONTEND_URL=${FRONTEND_URL}

# Stripe
STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}

# Redis
REDIS_HOST=${REDIS_HOST}
REDIS_PORT=${REDIS_PORT}

# PostgreSQL
DB_HOST=${DB_HOST}
DB_PORT=${DB_PORT}
DB_USER=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}
DB_NAME=${DB_NAME}
DATABASE_URL=${DATABASE_URL}

# Auth
JWT_SECRET=${JWT_SECRET}

# Oracle Object Storage
ORACLE_REGION=${ORACLE_REGION}
ORACLE_NAMESPACE=${ORACLE_NAMESPACE}
ORACLE_ENDPOINT=${ORACLE_ENDPOINT}
ORACLE_ACCESS_KEY_ID=${ORACLE_ACCESS_KEY_ID}
ORACLE_SECRET_ACCESS_KEY=${ORACLE_SECRET_ACCESS_KEY}
ORACLE_BUCKET_NAME=${ORACLE_BUCKET_NAME}
EOF

chmod 600 .env.production
echo "OK: .env.production generated at ${PROJECT_DIR}/.env.production"
